### PR TITLE
logging and submit-and-next-game button

### PR DESCRIPTION
**Pull request by karlorg**
Now we have a 'Submit and go to next game' button.  Also some log files appear in `generated/` while running tests.

The rules for selecting the 'next' game are a bit simple yet and, in
particular, don't support the notion of 'skipping' a game; you will
always be taken to the game that would be top of your status list even
if you started lower down.  Could get annoying when you really want to
ignore a certain game (eg. because it's much harder than the others and
you don't have time right now), but it should be good enough for us just
now.

Also this functionality is only tested at the browser level just now.  I
might be more motivated to add a Python test when I come to upgrade the
system to support 'skipping'.

### CODE REVIEW

**Comment by karlorg** [comment]
should probably also note this pull request includes a db migration

**Comment by allanderek** [comment]
Merged and pushed to prod.
There is a small bug, in that the 'Submit and Go to Next Game' button is enabled even before I have placed a move. But otherwise fine, I even checked that pressing it when on the last game took me back to status.

**Comment by karlorg** [comment]
On 26/03/2016 12:25, allanderek wrote:

> Merged and pushed to prod.
> There is a small bug, in that the 'Submit and Go to Next Game' button is
> enabled even before I have placed a move. But otherwise fine, I even
> checked that pressing it when on the last game took me back to status.

Have you tried refreshing the page?  First time I visited it didn't have 
the new `game.js` with that change.

**Comment by allanderek** [comment]
Oh, yeah that fixed it, thanks.

**Pull request merged**
