### PR TITLE
migrations support

### PR DESCRIPTION
**Pull request by karlorg**
using Flask-Migrate (https://flask-migrate.readthedocs.org/en/latest/), which is based on Alembic (https://alembic.readthedocs.org/en/latest/).

So far there's just one migration that creates the current database from nothing.  In future if we change the tables, we should create a new migration so that any running instances can use it to upgrade without losing data.

(Does this look like enough to get the running instance into a state where we can start a game that won't be wiped next time there's a db change?)

### CODE REVIEW

**Comment by allanderek** [comment]
Well I ran:

```
python manage.py remake_db
```

And got told to run `db upgrade` instead:

```
python manage.py db upgrade
```

But I got an error:

   File "/home/allanderek/Source/drunken-octo-avenger/venv/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table games already exists

So I did a `python manage.py remake_db --really` followed by another `db upgrade` but get the same error.

**Comment by karlorg** [comment]
On 22/06/2015 14:44, allanderek wrote:

> sqlite3.OperationalError: table games already exists
> 
> So I did a |python manage.py remake_db --really| followed by another |db
> upgrade| but get the same error.

The existing migration expects to be starting from nothing, so you'll 
have to delete the existing db to try it out.

**Comment by karlorg** [comment]
On 22/06/2015 14:45, Karl Naylor wrote:

> The existing migration expects to be starting from nothing, so you'll
> have to delete the existing db to try it out.

That is, future migrations will build on each other so you can go from 
one to the next.  But the first one I've defined is just for 
bootstrapping from nothing.

**Comment by allanderek** [comment]
I see, but then what is the point of `python manage.py remake_db --really` when is that useful?

**Comment by karlorg** [comment]
On 22/06/2015 14:47, allanderek wrote:

> I see, but then what is the point of |python manage.py remake_db
> --really| when is that useful?

Hopefully never, but I kept it around in case the migration system fails 
for some reason and someone needs to remake the DB the old-fashioned way.

**Comment by allanderek** [comment]
Okay I think I have it now. I did a `rm  ../db.sqlite` followed by `python manage.py db init` which gave me an error about a migration already being started. However `python manage.py db updgrade` seemed to work fine. I'm sure if I just knew more about migrations I would not have had any problems.

I don't know quite enough to say whether this will avoid us throwing away any current games in the future but it is definitely a step in the right direction. Appears better than what we had at a first glance.

**Comment by karlorg** [comment]
On 22/06/2015 14:51, allanderek wrote:

> Okay I think I have it now. I did a |rm ../db.sqlite| followed by
> |python manage.py db init| which gave me an error about a migration
> already being started. However |python manage.py db updgrade| seemed to
> work fine. I'm sure if I just knew more about migrations I would not
> have had any problems.

Yeah, the 'init' is already done and saved in the repo so we'll never 
need to do that again.  To get to current you should always just be able 
to do 'upgrade', either from nothing, or from a state created by 
previously using 'upgrade'.

We do have to do a little work each time we change the DB though to 
create the new migration.  The 'migrate' command produces a file with 
most of the work done, but the actual upgrade commands need to be 
checked manually.

> I don't know quite enough to say whether this will avoid us throwing
> away any current games in the future but it is definitely a step in the
> right direction. Appears better than what we had at a first glance.

Yeah.  To actually test it properly we need a DB change, but I don't 
need one right now.

I could create an unnecessary one actually, and check that upgrading to 
it and downgrading back works.  Not sure how I'd verify it worked, would 
have to create some code that uses a new column or whatever I guess.

Maybe I'll wait until it's time to save the identity of a game's winner 
and see if it works out for that.

**Pull request merged**
